<h1>Questions</h1>

<table>
    <tbody>
        <tr>
            <td><strong>QuestionID</strong></td>
            <td><strong>UploaderID</strong></td>
		<td><strong>Question</strong></td>
		<td><strong>Difficulty</strong></td>
		<td><strong>Rank</strong></td>
		<td><strong>created</strong></td>

        </tr>
        <?php foreach ($view->questions as $question): ?>
        <tr>
            <td><?php echo $question->QuestionID ?></td>
            <td><?php echo $question->UploaderID ?></td>
            <td><?php echo $question->Question ?></td>
            <td><?php echo $question->Difficulty ?></td>
            <td><?php echo $question->Rank ?></td>
            <td><?php echo $question->created ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

