<h1>Questions</h1>

<table>
    <tbody>
        <tr>
            <td><strong>QuestionID</strong></td>
            <td><strong>UploaderID</strong></td>
		<td><strong>Question</strong></td>
		<td><strong>Difficulty</strong></td>
		<td><strong>Rank</strong></td>
		<td><strong>created</strong></td>

        </tr>
        <?php foreach ($view->domains as $domain): ?>
        <tr>
            <td><?php echo $domain->QuestionID ?></td>
            <td><?php echo $domain->UploaderID ?></td>
            <td><?php echo $domain->Question ?></td>
            <td><?php echo $domain->Difficulty ?></td>
            <td><?php echo $domain->Rank ?></td>
            <td><?php echo $domain->created ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

