<h1>Question</h1>
  
<table>
<tr>
  <td width="120px"><strong>QuestionID</strong></td>
  <td><?php echo $view->questions->QuestionID ?></td>
</tr>

<tr>
  <td width="120px"><strong>UploaderID</strong></td>
  <td><?php echo $view->questions->UploaderID ?></td>
</tr>

<tr>
  <td width="120px"><strong>Question</strong></td>
  <td><?php echo $view->questions->Question ?></td>
</tr>

<tr>
  <td width="120px"><strong>Difficulty</strong></td>
  <td><?php echo $view->questions->Difficulty ?></td>
</tr>

<tr>
  <td width="120px"><strong>Rank</strong></td>
  <td><?php echo $view->questions->Rank ?></td>
</tr>

<tr>
  <td width="120px"><strong>Created</strong></td>
  <td><?php echo $view->questions->Created ?></td>
</tr>

</table>
