<h1>Question</h1>
  
<table>
<tr>
  <td width="120px"><strong>QuestionID</strong></td>
  <td><?php echo $view->question->QuestionID ?></td>
</tr>

<tr>
  <td width="120px"><strong>UploaderID</strong></td>
  <td><?php echo $view->question->UserID ?></td>
</tr>

<tr>
  <td width="120px"><strong>Question</strong></td>
  <td><?php echo $view->question->Question ?></td>
</tr>

<tr>
  <td width="120px"><strong>Difficulty</strong></td>
  <td><?php echo $view->question->Difficulty ?></td>
</tr>

<tr>
  <td width="120px"><strong>Rank</strong></td>
  <td><?php echo $view->question->Rank ?></td>
</tr>

<tr>
  <td width="120px"><strong>Created</strong></td>
  <td><?php echo $view->question->created ?></td>
</tr>

</table>
