<h1>Question</h1>
  
<table>
<tr>
  <td width="120px"><strong>QuestionID</strong></td>
  <td><?php echo $view->questions[0] ?></td>
</tr>

<tr>
  <td width="120px"><strong>UploaderID</strong></td>
  <td><?php echo $view->questions[1] ?></td>
</tr>

<tr>
  <td width="120px"><strong>Question</strong></td>
  <td><?php echo $view->questions[2] ?></td>
</tr>

<tr>
  <td width="120px"><strong>Difficulty</strong></td>
  <td><?php echo $view->questions[3] ?></td>
</tr>

<tr>
  <td width="120px"><strong>Rank</strong></td>
  <td><?php echo $view->questions[4] ?></td>
</tr>

<tr>
  <td width="120px"><strong>Created</strong></td>
  <td><?php echo $view->questions[5] ?></td>
</tr>

</table>
