<h1>Question</h1>
  
    protected $ChoiceID;
    protected $QuestionID;
    protected $IsRightChoice;
    protected $Choice;
    protected $Answer;
<table>
<tr>
  <td width="120px"><strong>ChoiceID</strong></td>
  <td><?php echo $view->questionchoices->ChoiceID ?></td>
</tr>

<tr>
  <td width="120px"><strong>QuestionID</strong></td>
  <td><?php echo $view->questionchoices->QuestionID ?></td>
</tr>

<tr>
  <td width="120px"><strong>IsRightChoice</strong></td>
  <td><?php echo $view->questionchoices->IsRightChoice ?></td>
</tr>

<tr>
  <td width="120px"><strong>Choice</strong></td>
  <td><?php echo $view->questionchoices->Choice ?></td>
</tr>

<tr>
  <td width="120px"><strong>Answer</strong></td>
  <td><?php echo $view->questionchoices->Answer ?></td>
</tr>


</table>
